### ISSUE TITLE
[Feature request]Add update() function to EEPROM

### ISSUE THREAD

**Issue by noisymime** [rogerclarkmelbourne/Arduino_STM32#248]
Would it be possible to add an update() function to the EEPROM library to improve compatibility with the original Arduino lib? 

Purpose of the function is that it will pass an address and data to the standard EEPROM.write() function, but only if the data in the requested EEPROM address is different from what is in the call to update().
Intent on the arduino is to reduce unneeded writes to the EEPROM. 

See: https://www.arduino.cc/en/Reference/EEPROMUpdate

I'm happy to put together a PR for this, but thought I'd raise it here first to see whether it will be considered.

Thanks.

**Comment by rogerclarkmelbourne** [comment]
Yes. 
I'm happy to add functions that are missing  if you send a PR.

If possible, when you edit the library code to add the function, so not do any tidying up of anything else, because if you remove a space or change a tab etc on any line, Git treats it as a code change, so its hard to determine if there has been a code change to a line or just a cosmetic change to tabbing etc
