### ISSUE TITLE
Make RTC prescaler uint32

### ISSUE THREAD

**Issue by me21** [rogerclarkmelbourne/Arduino_STM32#520]
The RTC prescaler register allows 20 bits wide values to be written, whereas RTClock library uses `uint16` for prescaler argument:

https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/8fa6bb45960097be75b6df6fc08705c85d4e4a09/STM32F1/libraries/RTClock/src/RTClock.h#L44

My device has 12 MHz crystal. The prescaler should be 93749 (12000000/128) in my case, but it won't fit into `uint16` argument.
The underlying `rtc_set_prescaler_load` function, which is used internally, already uses `uint32` argument.
Please update the library to use `uint32` instead.

**Comment by rogerclarkmelbourne** [comment]
Can you do a PR for this?

**Comment by rogerclarkmelbourne** [comment]
BTW.
It looks like you need to change RTClock.h and RTClock.cpp because the low level api function 

already takes 32 bits and seems to send write it into 2 separate registers in 16 bit chunks

https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/083e98801d71daefe4dfec4ac273daf2268ac5ad/STM32F1/libraries/RTClock/src/utility/rtc_util.c#L197-L206

**Comment by me21** [comment]
@rogerclarkmelbourne Please take a look.
