### ISSUE TITLE
pgmspace.h a few macro have side effects...

### ISSUE THREAD

**Issue by Hoek67** [rogerclarkmelbourne/Arduino_STM32#593]
Was trying to see if could get STM32F4 to compile under visual studio and visual micro.

Struck a few problems... 2 were my fault as had conflicts with pinmode.h and utils.h that were in my library that has since made me want to eventually prefix all my files and put into a namespace. These were hell to actually track down.

The other relates to the code below that I made work by toggling comments already in the code.  The commented code has side effects when calling var = pgm_read_word_addr((uint16_t *)memaddr8 + offset);

Unless there's a reason... can't all these functions just be the way they were... which seems the same as the way the 32 bit Arduino Due does it. (ie. just treat flash memory as normal read-only memory.

If readying multiple bytes over a 4 byte boundary causes an error... then that's a different issue as the standard Arduino implementation allows reading a DWORD from anywhere in memory without caring about boundaries. (ODDLY... found the ESP8266 code had exactly this problem).

#define pgm_read_byte(addr) (*(const unsigned char *)(addr))
#if 1 // dw
#define pgm_read_word(addr) (*(const unsigned short *)(addr))
#define pgm_read_dword(addr) (*(const unsigned long *)(addr))
#define pgm_read_float(addr) (*(const float *)(addr))
#else
#define pgm_read_word(addr) ({ \
	typeof(addr) _addr = (addr); \
	*(const unsigned short *)(_addr); \
})
#define pgm_read_dword(addr) ({ \
	typeof(addr) _addr = (addr); \
	*(const unsigned long *)(_addr); \
})
#define pgm_read_float(addr) ({ \
	typeof(addr) _addr = (addr); \
	*(const float *)(_addr); \
})
#define pgm_read_ptr(addr) ({ \
	typeof(addr) _addr = (addr); \
	*(void * const *)(_addr); \
})
#endif

**Comment by rogerclarkmelbourne** [comment]
The F4 core in my repo is no longer active maintained, because it has been superseded by ST's own official core. 

see  https://github.com/stm32duino

@stevstrong  has his own version of this F4 core, which has some improvements, but I'm not sure if its actively maintained anymore either.

Also. As per the readme, these cores are only designed to work with the official Arduino IDE, and because of differences between this and other third party IDE's its not possible to get it working correctly with other IDEs
