### ISSUE TITLE
GD32F103RCT6

### ISSUE THREAD

**Issue by nikjayswal** [rogerclarkmelbourne/Arduino_STM32#659]
Does Arduino support on GD32F103RCT6 and stm32dunio library ?

**Comment by rogerclarkmelbourne** [comment]
There was partial support for the GD32F103C8 board, but I commented out the lines from boards.txt because the GD32 didnt seem to be 100% compatible with the STM32

You can try and just use the STM32F103RC selection and see if that works, but it will depend on whether the board you have uses a 8Mhz or a 12Mhz or possibly even a 16Mhz crystal.

The GD32F103C8 boards I have, use a 12Mhz crystal and the variant files for that board are configured to use a 12Mhz crystal.

Hence if your board uses a 12Mhz crystal, you'd need to look at the GD32F103C8 variant files and see where the main PLL is configured and make those changes to the STM32F103R variant folder's files
