### ISSUE TITLE
STM32ADC Examples

### ISSUE THREAD

**Issue by nikjayswal** [rogerclarkmelbourne/Arduino_STM32#785]
Please ADD those 2 codes in STM32ADC DMA Examples.

```
dma_disable(DMA1, DMA_CH1); //Disable DMA and transfer

myADC.setTrigger(ADC_EXT_EV_SWSTART); // Disable ADC & DMA Trigger
```

**Comment by nikjayswal** [comment]
and Also PC13 LED Working inverted if i write High the LED is Off and if i write LOW led On.

**Comment by dewhisna** [comment]
@nikjayswal -- PC13 is working backwards because that's exactly how the blue pill board is designed. The PC13 pin can't source much current.  It can, however, barely sink enough current to turn on an LED at really low power.  So that's what they did in the design.  Therefore, writing it to HIGH is Off, and writing it to LOW is On.  That is NOT a code problem but because the designers of the blue pill were too cheap to add a transistor between the CPU and the LED to provide enough current flow and not run it inverted.  If you don't want it to work backwards, then redesign your board so that the LED isn't wired inverted.

**Comment by stevstrong** [comment]
@nikjayswal , in which example do you mean?

**Comment by nikjayswal** [comment]
STM32ADC "SingleChannelAtSampleRateCircularBuffer , MultiChannelSingleConversion , MultiChannelContinuousConversion "

Those two lines is useful to disable the DMA and ADC Trigger to avoid analogRead errors "please add those two lines as a comment in Example sketch".

**Comment by stevstrong** [comment]
Can you make a pull request?

**Comment by stevstrong** [comment]
I will close this due to inactivity.
